language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run eslint
  - npm run sass-lint
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  - provider: npm
    email: software@pod-point.com
    skip_cleanup: true
    api_key:
      secure: I6zDfnijguAhU/yOh9L4FKAvLeSKjR1p+jhROhQBWKPCUBHD0EZoKZvnNFTFjXdFLUqzjP/VEpaer0j48HoLX7Q0FJihIGIgAoSqOAB3D8/F2ToeyJcj7biERo4NqZ1CXXx+2AzloX42EueqiWhl/RtwxWaVMI/vdUKHTrG2V0B7IgeqT7cFkOCnXN3TrbuanoTfV5XSx5dvouHeO04cKDyUoWWMq69oDn7YD6Y2wsG+PiCME5MDXAJBgEkGKWDNl+4krUD2hEcOg9I4U94sf2QNHIIVfbLho1SN3EOMXupeptwmqc7WBKFQDak0vxDm7Io/qQMb2RebCFJixdlbl0MJILiEocghvWZV5t1rUz6BdH8IsJyNJ72SuxHh6JfzbesBArxQKFpmhDOhv12fRLUl1fuRcNWKjTzK+5IsHgzUYIKYBhVZFGKPGZxmy3uVzykGMZwDXAokMDf56b0O2hRdmVsZdprMeYhg4GUq7ga2dQXeF68hdeXs/yvo0faAl9v2rhnU3pDXsxFJfgvBxTeIKfCiOdK1hTRb8AvxTN4bx+JRPyMtBCOWK9MWQ6LFdikbm3EJ9H3OIefuEeYQX0HVYdyB2SXf5mnR1Dn/zuaVLx6hT574f1t1MNZauXA5GC9q4hx0VIpJLIhqSUXnLG0xMMQhiGrxpTgy2s9Qf8Q=
    on:
      branch: master
      repo: Pod-Point/pod-point-ui-toolkit
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
    github_token:
      secure: NkVxXwh1f6P7FuNrSpyUst9Iih+3tLerOFlK8EfBeOUfyvMdGOTa0yWnq0tv0e/N3Xx++IYao3fvbKkYDrJNfN1a53nbIsXm8zyEzr9To8Im2N60TbK6j8y4lhO3viX2DcQUMBRcJW/9Cp0/GCc7D0Ov/gB5wiwx2qQICIsIGQg4Z4Ym9fLwjX71eeQVXHGsMWFoAkO9gOSisgMnGb336rAazzbsAkAyryAc/QYYvoJDD0OZyU6cX1C3aDdBLGhbrgbzPjC5vwTMn5N3cMvo6tAANV9M2YodylF5G9eYatsK3sakL/PviKAHs8OaW2Odzm+Pju/omtiIH6eax74zp/iZ84r7DXe4IPnK2oKEKWw7Qln1Dki0MWQWTooCnw4W0BNsqDnP3vAOm+xc+suhE/EezSFvt5biVV2kCI6MWTUyWR/4QvJp48hTKpsDZ2uvEJeATP13HYAiWG6GBuEaSoScyEpGfZHs5w7oVdLeF+bO07Xofezo+HBqrO4ySpBG2m1mhmZ08OFu/GERozgj8Bc4Ww/tFay0nAECOYmqCgn+EQOHVZxIWdt7EUJQ/jJZ/C1T9zwb/VAHoHkoW/LCkvauZsJSalkg7JNSM2DnjOvQ/6au9TZQ4Xp64tjFIy1QSlVugjiWqC3Gu0M4pxip1eRJ6Yp8pHrwAiOe648/V+w=
