language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run eslint
  - npm run sass-lint
cache:
  directories:
    - node_modules
deploy:
  matrix:
  - provider: npm
    email: software@pod-point.com
    api_key:
      secure: f1qdCkQNNdB5lXzGZRCfBllrDJInGt2yph1NNnoOaOgXXU8Vo/zXjYCH9i6u0earkwJwZtqPhHuY4OwIy4JL8kgXwPwP2yfsvw33n42rJj1Zx+iFbY+KZYqT58KcELxPKPfW96F6penv8dPktXkZ80dzSTCuQaw4CTakbMZGKQacgMPpxi0X9bommyWUjYpgQVGlckbmOfLZYfaoPCFzdLDp/rkSUNv69O77MKLTjO1qpsPopnUF6UBT9POXRjLFW3cyViZoxTlOwI2r62+SRQTAlio4nhiLEBKDmIzG1gYDd2CdvWdKcJO9lk52mICutzBLxg5PaM/0L4J4MPjdCZHOYdQ/x3ARBr6a/Zg/uTR5cMTa3leIArIvysUhNIlntFL2VFgUO8w4B75KdGKW6t5Xeki4A+t9kYFwhSkxI8JZtiu8woTTLUUzjDNcpxE00SJSHA3YXnEZiSXFOXrRypeCdbMqgmefVvVJdEe7hh0M+H6ieGuv0NIK3u9kq2Bcc8FJBv7J+GnhEZX6qADPPLTHSj59J5VtdEYQE6tSOm6XGPG+5PTundF3wjlvnddm7tedUV91AuclSb56Jpx/pImFkCgRbbGJd6TXlHzThDqD95hepwqRgSg5sA+Px7w8A5kKQKM3HxGCi3iUwiwh/CwvEAsvPjbfH7k+H6GYdxE=
    on:
      branch: master
      repo: Pod-Point/pod-point-ui-toolkit
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token:
      secure: gY8bTI2hWf5c2noyReo0KUV6nnzCo1rzVK8ys1cnHkcF0/N2AtmLPOTA9hB12D35n016wxNon4MTODMas8q9eWyqwWzj/cZmVYT/vIeMbdKSUOSesvyB1koTZNUU15cpB4IGKOesGdw6ZAVuebJzAGa8BsFdlDHw0n9cIKu7TAFFLQwd/hd2lRdPEn4UvueFiqK/vUtgaSTz16ANvPxPx3JnfgGqY+OQxigV2UoViPJ12MKKl4wckaccRVC5isPQHPmDHe1N74v99NRofxVYlK5qYRfWzSqoHOqMu6spB7xM2UbIzq+NCqZQBAnKHSE/mX6YMBrqAYq4wm1af/+ccwsITcPot3fVGPmVl0decbYM7x2F0iunjPJZ5yyVw6OCuaCZYIDWo+V+t5VgH+jGwIrDGUwgEel69mfdaoOfPmA08rIE7EuOiHtelC/XnQTG5metMrNZXQqmZcA2VqICG3oOcd+EIxKengrDX01l1D6meNO63xWtYWKdi/XMSUgB/rqxYZJvnePkaO0twaEH5kvE4M3ayjoXgLdKsPw8ANGoKCAYLYiJUSC6fSRj1vBRco1Lfh1NqR45PHOVcxSZnrTNGozeb8BrVJad3eo0ExnRDAJmj+pwcJxBB52zf9NDDT8CJ/9eV0NwsKr+rHIF1i6SzwsHFg8h5PlS/VJA9tI=
