language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run eslint
  - npm run sass-lint
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  - provider: npm
    email: software@pod-point.com
    skip_cleanup: true
    api_key:
      secure: ZKJRBjH3BkmaBHhzUL9osJ50tyrFL7LTSYVkUBH915PNqhvS2a5P4sH9HnuMi/I7rMT53e6TWRiyZI3aJkFM5pw8aBxd4xCrqPoBK+meLElPjERKtLFRu6ALzQSq/atNAWPNK3eaGSsF7sWr21hMt5ZuZLCpIHYcXuvNOmw+RFjfrSNpzC7akhov2muFxZwd4EyfftqMXeW52RK63rNZY6/bUkOhMdlIrJCTn3fGqQpTNxse/ab8K9S+JJCs0K+3gtR9rS0K+yLRGRjjwIU2RDSCyEPsuwJxWnmJz81lD89iOEnAerBmyRQm24QbjOkBdeHff7GIzT8cOBkyiLrFUYAb4YAdWT+InmMKdFdvMM3FcuRs59XxmEseP1WwmN79K1ewL5iRwsdmvV6FI/9zBnxhmevcKCJ6t9E3udtLGXuuKApUC/2VKwjt4Pp4/OHverKOmHaxnzkoOLl1X9pVW9v8b1mcAalKcoQAtx6tRz6df38JTMGunetnkNmIy45sLjk9GRDwLu3LjC0WcF9YbijNLjBqhbODoezn2DymXdcQ9/WDmoZjKNcctMCddIM74Jt6GMfd2pjdUpoJBy7Ws0biXltBO5qKR3KjN8l5bWHlvANugoR1vfX37EtLXisb/TkDx9pri6lHoIkR3iwvGbkhHTFGJ1wDffJk1m8+7ik=
    on:
      branch: master
      repo: Pod-Point/pod-point-ui-toolkit
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
    github_token:
      secure: NkVxXwh1f6P7FuNrSpyUst9Iih+3tLerOFlK8EfBeOUfyvMdGOTa0yWnq0tv0e/N3Xx++IYao3fvbKkYDrJNfN1a53nbIsXm8zyEzr9To8Im2N60TbK6j8y4lhO3viX2DcQUMBRcJW/9Cp0/GCc7D0Ov/gB5wiwx2qQICIsIGQg4Z4Ym9fLwjX71eeQVXHGsMWFoAkO9gOSisgMnGb336rAazzbsAkAyryAc/QYYvoJDD0OZyU6cX1C3aDdBLGhbrgbzPjC5vwTMn5N3cMvo6tAANV9M2YodylF5G9eYatsK3sakL/PviKAHs8OaW2Odzm+Pju/omtiIH6eax74zp/iZ84r7DXe4IPnK2oKEKWw7Qln1Dki0MWQWTooCnw4W0BNsqDnP3vAOm+xc+suhE/EezSFvt5biVV2kCI6MWTUyWR/4QvJp48hTKpsDZ2uvEJeATP13HYAiWG6GBuEaSoScyEpGfZHs5w7oVdLeF+bO07Xofezo+HBqrO4ySpBG2m1mhmZ08OFu/GERozgj8Bc4Ww/tFay0nAECOYmqCgn+EQOHVZxIWdt7EUJQ/jJZ/C1T9zwb/VAHoHkoW/LCkvauZsJSalkg7JNSM2DnjOvQ/6au9TZQ4Xp64tjFIy1QSlVugjiWqC3Gu0M4pxip1eRJ6Yp8pHrwAiOe648/V+w=
