language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run eslint
  - npm run sass-lint
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  - provider: npm
    email: software@pod-point.com
    api_key:
      secure: IZsbKIzr0qTpRK+zQGlk0WdrAnjQMLQKLSu126EMrOohs3XA1yioHzCvPSX2v2XfjTa/owRCjTf/3cbVTcbN1bZLGpVyI3//PxvWF/h4mFDKRKVl+8uRuLGH+UJMApt0KP55xHQKJDov/HKO+1q45OkxGWF1fYOoqLRpKnKoiEr8lGJw4KhxA2s5QF9UPcD75RhAacVJhxUzMG/eNPmc6Rcq1LaDx/DnMz/Ts7Mu/Ls9CIEZZqKOL1NxOfN+Z2ei0QpyJVrqLa9MCZ0WUmK121tsdCpZse6y9P5iiOYDwwRNJuZHDPzdFcuPP4iPkatfARqzd+FMbVqsmGqDtCMuekvHEaD9iB8IlT6C7/mmJncwZPV7pnRl+LR0zNlrVSfql4ftIcjzLkj+l9bn3gaosrzgBH226kBHQ6RIQsb6u2Qk1WyVKw1c3zD4ynO5SA1hM+pAUFI0NMTfziRoL+col/I6DjIfRvSxa2tJMFOo+g8uwuSYNT081KHn6z7hnNqy5hzpNFccDNHn3oGR6jBS1z2RE2xpdpiMrkIc/hdqtjc0VR/3JgmWXw0tYN4H18wJDYqyl8lDbRl91YT2BIV38r5YWvOzsCwAUKHEtaFtz8TxZtpfI6RadN1RdT64JKxXXNL0sD1d60XYzqjxTpuBT05maxoBBl+YaSPU+waiO2Y=
    on:
      branch: master
      repo: Pod-Point/pod-point-ui-toolkit
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
    github_token:
      secure: Pgev+5vsklCDnpqGIiKAF2yDEqTuNVxaZOUsskaoxK0FEGY33/ZptBDzbFG5lK+PJXY8c6sMWtWrm66F+BcqZErJU/KhD3dFcDqqoL3am/JGZ4UWzhIHYUYba4LbQRsb7GafBGTXKr0s2REyRTIko4Yw8VcSK8Qb3urPnjW/cy8XjfagbGtJRkgGDAQJOefuraYFo5lbNlIJF/q+yoylRsrmvuVLf2fH0V1LXgNuDS3lTmOl62YwrOREA2GdPBXcOhZFf6/Po+hEj3Agx8F1hVro+GlzAVmefK+KMhe6hRZdyckelY9eSBSR90YyMz4dA8XlNmnijyWgHz7JARJdp89uohKoXNxqqlrAusUbFVIKKdRcwyVypromlUr3X28s2N4f8/JwTBpEInrE4z9a0RMb/QOpA9bxwcz6qzfuPkdvpK+tdJdUc8YKl0FWAPa8AXYc7yYdLD05icLBHPmF3V9wdJIrdWjXwsobI7pjNNsofIbR+XnLwIu1+DN7c1yVoszJjhiUAX2s1p2pEUGahzvfwn9okpTiWRQAWCdodYJ1RhenlnIgz/ccZ76a4uiD3aKrvw7WTKnBJyeGsY7TNmGlFb5FuossQWLciphsMd1gROzUxI/jUBBMD7qbxwWNkPOVZn/I6s3u+mBVWL3PYyIfS7b9fB2PyMy0fMMSFoc=
