language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run lint
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: software@pod-point.com
  api_key:
    secure: WW/oqmqcK1p796avFvWqs2SS7GmTPD3vGQ2eLu4HQGDqk7m02UA8CZajgcMrkrr0ozI4uiI3RJwDNa3wLdc07CPt9lYLL7eZuvFfKszSGaKInaOhDOFVlp4t2RWjidu3dRQrcxOcHeQ+9giUvsO/OZnNQuLNxoxmViMqNQuZpVHvImG5OQPwSvYp8Gn8ch39ap96lzNUgZHytioDY3mKYIKuSGLN7HEl2LpK90L5rAPpa29xs7aPiqit/KAKW8DLTakFi767xq3pK8DCbvPGiA45nUXLp/qv5xI6llqc36i2yC6q04SZkM+oSmHxhFf27Wnn6erXHoyH6gcJXj5LH2uGv99aDbVEdOUF4cJHTZIH9IxLuIha6yZACB6EOBTSCB+Pxvy+j+w9DI4bWdRwOQfYhviESNKgKHFRs5pRNwo5SXreXmqAcVVICxBzLcarECG2WJe7GXNFkKbFTzQcgauoEWXDqJyP32VbmlPNtYA9j8Ig57Ww0+PQYs9Li4IiIXDZuK5hmi503lI0vjTX8KZ2VKU1zBlPIvKQXgl2e4ZHnuNAJSj2kRCM7dLrsJj5Ohf1YHQ5IAV8VNnOBCoTTE4wht0xNF7coBWfN0zlmbBGDKUBtV6ZXC4BJ2EEJa4PRU2PnABREkkXRtlyt4DrpRiD6zlHlnr/ftSrJUaQgUM=
  on:
    tags: true
    branch: master
    repo: Pod-Point/pod-point-ui-toolkit
