language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run eslint
  - npm run sass-lint
cache:
  directories:
    - node_modules
deploy:
  - provider: npm
    email: software@pod-point.com
    api_key:
      secure: cHhX0zOaxHw5IT2oUw0MspmSXE11iyervwAYq2XPHRX1M9avPwhXuy7zrsxhOhkfGvCi2YxxZWzc8GWdfe2Ki5S633Az+eWvt0Jz1oQhGynJPVCKY+yBKScgMl9BFgjczv/4rxMxJg/nzgLiEmsq70QCXXL8PbtTCcCRbHN722SZOU/SiyH0dh4HsRi+AP5iPadoLCPodXNnf7WWuWSlYdywCZLz70lD73cJ7/dFQKiMO1nCE0pj7sDCBCfsKiL2783XnG3piKGAV7kD5xgR2toFJs95Z05vyDSqCHZYoqjs6B7NFrwSa3rzjgfhua6aJiuWlAokn4P5jPvupMLW76BaUn516Yv5doCCZUyXoWEXKVRXowiuxPgrbDh2OC7hpsHaYPRn6aprEPNZfX9WdgSeZmhCe6KQa67iXCnTvYlSj/tZJt5xKxWEHp94XUnhdW0lNbb7R8KpVkU4Vucn10wVbvumEYEOvp9PQ6Cta7dIWPgR8R0o/wcnDE+UeCeHIpy3N0LV+iYcZI4qzBGQvzABlThg4iLMAu0slbt+9rMomisOctclBhwL21Is8VSmb01oDY3cmLAb2qw6IZLdfoQBpfG8eypnijd11fzagrHbMs/ekPlE5q4pbJLgaaeloJs6a5RMmZzlOtthYz2gCyhkLJ+liViDStKUq02kVbE=
    on:
      branch: master
      repo: Pod-Point/pod-point-ui-toolkit
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token:
      secure: omUHeUsr1QYFnmSsB3I4ut8MIFvW9xxOVegjh70LniHXw3queG6Nz0G4FXNPK4XSAFOhje2OiG4TsM6d/E5xh0Iy4JoSuFpIHuPdmR0qlIj6+7ax2ALi17Bkk4edA4FBuy5vFZel9jhtm8JQMmJ3TPW8uVjbF9O1yPpGQAp+yTGtOvK186v0TxUdDucvCPydj5URbknGWALCb78KgDLf5C55yTGkHGISdTD4Uevi/gvBw9G1jiNQhnE8t/zVXjKCa52QHPyAExmVqHgsFYvjlwh8Xg7VFttgRBlm1HPaoHfiD61PPef1evVsqLAHJI4EBH11lnjL1D1SwvnhMJ9V4Rkq2GS883Lav4bUb750JUCFgX9j4K3S2RLKhYP+GJp6XIMZ3CAHN7yhWbynbUQmI2RykTnOTNmZnet5auAU5tV6P9tNP2fWWNEAPMyfa66AcKV+2aZu4hHjy8C+yDh2MljD87U6mrh07fOYB3gyplMHNwCAhFSmBajd63qNjapabCfd1Bc1nGyHXJlSwiX7QF+5nFsLJsMc0zJYmEZ2yHpVgNS0IZtwgV/XCkr5lBDd0+lH8kL5eGjAUX0tj5iouMGYNfdmcv7z4gyroDTq7VrVo8GFVGFX5I3Emlw/UXCZq9s02re4Rg7i/cZ2ucxGW40wctp6BCM6yvEu7lU3fr4=
