language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run lint
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: software@pod-point.com
  api_key:
    secure: r/mmUsru/4sstFKSzWGtO6FPS4poqvdxTvhVxHRDKTx3JlKBfin1xqqqbDR2sc0Vj4m5R1lHwETHHDpg2vUE5Bsb6QJZNWx/ALL+iknuzLrF+YYiBtjmmo9UKZYi2sQEM7Oj1B3ToonGqBu2MkIRKA2XAIRC0ePTxDanqXMnOiPqZiY/AH3VoTmACy5z5RKKZwvKN8O82JwUlLqeZqvSJkGeH0oXJ9ak1vgTFsdHLtE+9nK2+ImizGv+dNoYHeug+CcVgE0bsZ6SvOfH9NAQ+NHNfx0gKnF+tGGR1BteoAGC/V6lDpWy9VAV5KRzrjQ5fYelMPgD+Ju0Sm/Id0wKRxKNv2fVRjcgMLa3V/flUXwl/4aeY7MbghX8oMbqldpgU2zL5dywbqCuapZ2beZXvXaZu7huUCf04XyQeWPa14w+pw1ya8IWCRW+21KmP1vw3Xts+kFMSkW+HAIJa0c9skaaT0B6OrqTRCqAyLqGa94dplAiEwLT/vVamusCyaM0Tz4+vW2nlgG6bbnK3my61qhBB3/3LJJFgccLNXm//URhELKgDIxxuz63EvMWyXvblo6+KC03coC0DsfxpGRHvRU6VTBBwWCA8QdzJKCkA7yYy/qaXFHCeBWSWJbF3JH2Tpr6TKadIBNcVj2AJBHr9WfHJzsz1EjQJ35PHcODFQY=
  on:
    tags: true
    repo: Pod-Point/pod-point-ui-toolkit
