language: node_js
node_js:
  - 6
sudo: false
script:
  - npm run eslint
  - npm run sass-lint
  - npm run build
cache:
  directories:
    - node_modules
deploy:
  - provider: npm
    email: software@pod-point.com
    api_key:
      secure: IZsbKIzr0qTpRK+zQGlk0WdrAnjQMLQKLSu126EMrOohs3XA1yioHzCvPSX2v2XfjTa/owRCjTf/3cbVTcbN1bZLGpVyI3//PxvWF/h4mFDKRKVl+8uRuLGH+UJMApt0KP55xHQKJDov/HKO+1q45OkxGWF1fYOoqLRpKnKoiEr8lGJw4KhxA2s5QF9UPcD75RhAacVJhxUzMG/eNPmc6Rcq1LaDx/DnMz/Ts7Mu/Ls9CIEZZqKOL1NxOfN+Z2ei0QpyJVrqLa9MCZ0WUmK121tsdCpZse6y9P5iiOYDwwRNJuZHDPzdFcuPP4iPkatfARqzd+FMbVqsmGqDtCMuekvHEaD9iB8IlT6C7/mmJncwZPV7pnRl+LR0zNlrVSfql4ftIcjzLkj+l9bn3gaosrzgBH226kBHQ6RIQsb6u2Qk1WyVKw1c3zD4ynO5SA1hM+pAUFI0NMTfziRoL+col/I6DjIfRvSxa2tJMFOo+g8uwuSYNT081KHn6z7hnNqy5hzpNFccDNHn3oGR6jBS1z2RE2xpdpiMrkIc/hdqtjc0VR/3JgmWXw0tYN4H18wJDYqyl8lDbRl91YT2BIV38r5YWvOzsCwAUKHEtaFtz8TxZtpfI6RadN1RdT64JKxXXNL0sD1d60XYzqjxTpuBT05maxoBBl+YaSPU+waiO2Y=
    on:
      branch: master
      repo: Pod-Point/pod-point-ui-toolkit
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    on:
      branch: master
    github_token: $GITHUB_TOKEN
env:
  global:
    secure: ipwW8a0bpsGKBBwFnHl5148Mp2fGhigmvNXqFl8ruyily7sZOMGfLVIuDppndteDG4GGpXcWdPjLr1TuIqfz8svZu3fePb7wj2ygLbi5zn2qmuTvxYcQTNq3wGbmaT+xN/zGYeQl9U5Q6BpVVPjFegIyhH/SiiJjOtGf4gaS409NKTOyvxkHn3zP42Tm1twFZ1ZlgmpokLZqJYw+NdiOxi2lW+80jYDVArO4eVdAPNLCWPyALLmrXWUFTCygBZYTPbeKDmd23RzhWO9XmOhdXdV2Xfj2SRtqrbPF303APeypMYebZHpLmdWg9MOf6hFj2fy+CulrdceeKX92TPfZFc1DM8NC8YPYcirEBbkeP01XiQyMAvwfB5Pj9Lyd5i7LY7CiwD9MQLrLg+5A5tKluj4Uz1s39t/eOqiWaBrHk1x/aUBjPwunPxVSobAIu/cRg40rKqBziYWi32b1tUu0ugUSZx34f8tsRbWpUnAJ3lad80Q6oPfg6G+yHPKHkzLXxTg2OyxAKCHPyOSRmxIT9DK/nbqA0One8icVzV+AiIkxJgoChHgSVI469EhI/oGSUykfsdzIKOUmxHfpYGs8Lis+UHLpEgosnzVJkszAY5UTPtqsGoCsaNg0Zvz4ryfVhzxMVKl2lIZSBz7dnhD9IGvT/aI21HO7hcnZPokzbog=
